import {
  IconAlertTriangle,
  IconArrowRight,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconProps,
  IconShoppingBag,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconMinus,
  IconSettings,
  IconSun,
  IconTrash,
  IconBrandTwitter,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX,
  IconLayoutKanban,
  IconBrandGithub,
  IconDeviceMobile,
  IconUserPlus,
  IconHeart,
  IconBell,
  IconSearch,
  IconMenu2,
  IconHttpQue,
  IconBookmark,
  IconFlameFilled,
  IconShoppingCartCopy,
  IconExchange,
  IconShieldCheckFilled,
  IconHeartFilled,
  IconBookmarkFilled,
  IconStar,
  IconPackage,
  IconMail,
  IconMapPin,
  IconBrandInstagram,
  IconBrandX,
  IconBrandTiktok,
  IconBrandWhatsapp,
  IconBrandLinkedin,
  IconError404,
  IconBuildingStore,
  IconLogout,
  IconEdit,
  IconCopy,
  IconEye,
  IconEyeOff,
  IconCirclePlus,
} from "@tabler/icons-react";

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  logout: IconLogout,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  minus: IconMinus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  phone: IconDeviceMobile,
  userPlus: IconUserPlus,
  question: IconHttpQue,
  heart: IconHeart,
  bell: IconBell,
  search: IconSearch,
  menu: IconMenu2,
  bookmark: IconBookmark,
  flame: IconFlameFilled,
  cartCopy: IconShoppingCartCopy,
  exchange: IconExchange,
  shieldCheck: IconShieldCheckFilled,
  heartFilled: IconHeartFilled,
  bookmarkFilled: IconBookmarkFilled,
  star: IconStar,
  package: IconPackage,
  mail: IconMail,
  mapPin: IconMapPin,
  instagram: IconBrandInstagram,
  x: IconBrandX,
  tiktok: IconBrandTiktok,
  whatsapp: IconBrandWhatsapp,
  linkedin: IconBrandLinkedin,
  error: IconError404,
  store: IconBuildingStore,
  edit: IconEdit,
  copy: IconCopy,
  eye: IconEye,
  eyeOff: IconEyeOff,
  circlePlus: IconCirclePlus,
};
